name: bayfin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg_provider: ^1.0.7
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
  flex_color_scheme: ^7.3.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  provider: ^6.1.2
  cloud_firestore: ^5.2.1
  firebase_analytics: ^11.2.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  http: ^1.2.2
  fl_chart: ^0.69.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bayfinlogo.png
    - assets/images/googleimage.png
    - assets/images/aktienbild.png
    - assets/images/amazonlogo.png
    - assets/images/hmlogo.png
    - assets/images/vodafonelogo.png
    - assets/images/nikelogo.png
    - assets/images/swsglogo.png
    - assets/images/boschlogo.png
    - assets/images/klarnalogo.png
    - assets/images/platzhalter.jpeg
    - assets/images/platzhalterfinanzen.png
   
flutter_icons:
  image_path: "assets/images/bayfinicon.png"
  android: true
  ios: true
  min_sdk_android: 21
dev_dependencies:
  flutter_test:
    sdk: flutter