name: bayfin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg_provider: ^1.0.7
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/bayfinlogo.png
    - lib/assets/images/googleimage.png
    - lib/assets/images/aktienbild.png
    - lib/assets/images/amazonlogo.png
    - lib/assets/images/hmlogo.png
    - lib/assets/images/vodafonelogo.png
    - lib/assets/images/nikelogo.png
    - lib/assets/images/swsglogo.png
    - lib/assets/images/boschlogo.png
    - lib/assets/images/klarnalogo.png
   
flutter_launcher_icons:
  image_path: "assets/launcher_icon.png"
  android: true
  ios: true
  min_sdk_android: 21
dev_dependencies:
  flutter_test:
    sdk: flutter